/// <reference types="react" />
import { onBlurType, onChangeType, onClickType } from '../../utils/types/typesUtils';
import '../../styles.scss';
import './task.scss';
type submenus = {
    id?: number | string;
    className?: string;
    onClick?: onClickType;
    title?: string;
};
type prioridadTypes = 'baja' | 'media' | 'alta';
type optionsType = {
    id?: string;
    submenus?: submenus[];
    title?: string;
    onClick?: onClickType;
    className?: string;
};
export interface TaskProps {
    principalTask?: boolean;
    taskDisabled?: boolean;
    taskComplete?: boolean;
    isSubtask?: boolean;
    check?: boolean;
    valueTask?: string;
    valueDescription?: string;
    onClickCheck?: onClickType;
    onChangeNameTask?: onBlurType;
    onChangeDescriptionTask?: onBlurType;
    idCheckbox?: string;
    onChangeCheckbox?: onChangeType;
    plantillas?: boolean;
    onChangeDias?: onChangeType;
    disabledEndDate?: boolean;
    disabledStartDate?: boolean;
    onChangeEndDate?: onChangeType;
    onChangeStartDate?: onChangeType;
    startDateValue?: Date;
    endDateValue?: Date;
    className?: string;
    durationValue?: string;
    responsables?: submenus[];
    equipos?: submenus[];
    revision?: submenus[];
    valueResponsable?: string;
    valueRevision?: string;
    prioridadInicial?: prioridadTypes;
    onClickPrioridad?: onClickType;
    moreOptions?: optionsType[];
    onClickEliminar?: onClickType;
    onClickRecordatorio?: onClickType;
    subtaskForbbiden?: boolean;
    Children?: any;
    onClickCreateTemplate?: onClickType;
    onClickAddTask?: onClickType;
    templateOptions?: optionsType[];
}
export declare const optionsPlantillas: (templateOptions: optionsType[], onClickCreateTemplate: onClickType) => optionsType[];
declare const Task: (props: TaskProps) => JSX.Element;
export default Task;
