type iconsType =
	| 'pautar'
	| 'minimizar'
	| 'orientar'
	| 'trafico'
	| 'sitios'
	| 'urbanos'
	| 'outdoors'
	| 'indoors'
	| 'vallas'
	| 'dashboard'
	| 'cotizador'
	| 'bloqueado'
	| 'desbloqueado'
	| 'implementaciones'
	| 'carrito'
	| 'carritoForbidden'
	| 'edit'
	| 'map'
	| 'share'
	| 'pdf'
	| 'download'
	| 'excel'
	| 'kml'
	| 'save'
	| 'delete'
	| 'previsualizar'
	| 'noVisualizar'
	| 'boards'
	| 'conIluminacion'
	| 'sinIluminacion'
	| 'iluminacionIndiferente'
	| 'vistaNatural'
	| 'vistaCruzada'
	| 'sinPreferenciasVistas'
	| 'categoria'
	| 'circuloPersonalizado'
	| 'busqueda'
	| 'clave'
	| 'coordenadas'
	| 'reordernar'
	| 'puntosSupensivos'
	| 'direccion'
	| 'filtrar'
	| 'aeropuerto'
	| 'centrosComerciales'
	| 'maximizarCampos'
	| 'plazasInteres'
	| 'tipoExhibicion'
	| 'logout'
	| 'noPerifoneo'
	| 'conPerifoneo'
	| 'ubicacion'
	| 'flechas'
	| 'timeline'
	| 'newUser'
	| 'dificultad'
	| 'recargar'
	| "calendar"
	| "reloj"
	| "prioridad"
	| "confirmar"
	| "close"
	| "seleccionarTodo"
	| "ampliar"
	| "arrastrar"
	| "billetes"
	| "busquedaEmpresa"
	| "catalogo"
	| "ciudadesInteres"
	| "cliente"
	| "comentarios"
	| "costoCliente"
	| "costoIMJ"
	| "add"
	| "datosCliente"
	| "datosCampania"
	| "datosFacturacion"
	| "diamantes"
	| "ajustes"
	| "herramientas"
	| "home"
	| "inventario"
	| "caraBilletes"
	| "monedas"
	| "operaciones"
	| "oro"
	| "pautadoInteligente"
	| "pautadoTradicional"
	| "pautas"
	| "planning"
	| "centavo"
	| "preferenciasProveedores"
	| "preferenciasUbicacion"
	| "regresarVistaCards"
	| "tareas"
	| "list"
	;
export interface getIconsInterface {
	children?: any;
	size?: number | string;
	fill?: string;
	icon?: iconsType;
	title?: string;
	strokeWidth?: number;
}
export interface iconsInterface {
	icon?: iconsType;
	fill?: string;
	strokeWidth?: number;
}
